// Auto-generated by TagEnumGenerator
public enum Tags
{
    Untagged,
    Respawn,
    Finish,
    EditorOnly,
    MainCamera,
    Player,
    GameController,
    Bullet,
    Enemy,
    Item,
    FxTemporaire,
    Pet,
    Manager,
    SpecialMove,
}
